<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
const router = useRouter(); const loading = ref(false); const error = ref('')
const form = reactive({ base_url: 'http://localhost:3000', school_code: '', setup_token: '', device_name: 'KruDee Kiosk', role: 'both', admin_pin: '' })
async function submit(): Promise<void> { error.value = ''; if (!form.school_code || !form.setup_token || form.admin_pin.length < 4) { error.value = 'กรุณากรอกข้อมูลให้ครบ และตั้ง PIN อย่างน้อย 4 หลัก'; return } loading.value = true; try { await window.krudee.setup.register({ ...form }); await router.push('/kiosk') } catch (err) { error.value = err instanceof Error ? err.message : 'ลงทะเบียนเครื่องไม่สำเร็จ' } finally { loading.value = false } }
</script>
<template><main class="page setup-page"><form class="card setup-card grid" @submit.prevent="submit"><div><p class="muted">ตั้งค่าครั้งแรก</p><h1>เชื่อมต่อเครื่องบันทึกเวลา</h1><p>กรอกข้อมูลจากระบบ KruDee เพื่อเริ่มใช้งานคีออสก์ RFID</p></div><label>URL เซิร์ฟเวอร์ KruDee <input v-model="form.base_url" class="input" required /></label><label>รหัสโรงเรียน <input v-model="form.school_code" class="input" required autocomplete="off" /></label><label>Setup Token <input v-model="form.setup_token" class="input" required autocomplete="off" /></label><label>ชื่อเครื่อง <input v-model="form.device_name" class="input" /></label><label>โหมดเครื่อง<select v-model="form.role"><option value="both">เข้าและออก</option><option value="entry">เข้าอย่างเดียว</option><option value="exit">ออกอย่างเดียว</option></select></label><label>ตั้ง PIN ผู้ดูแล <input v-model="form.admin_pin" class="input" type="password" inputmode="numeric" required /></label><p v-if="error" class="error" role="alert">{{ error }}</p><button class="btn-primary" :disabled="loading">{{ loading ? 'กำลังลงทะเบียน...' : 'ลงทะเบียนและดาวน์โหลดรายชื่อนักเรียน' }}</button></form></main></template>
<style scoped>.setup-page{display:grid;place-items:center}.setup-card{width:min(560px,100%);padding:32px}h1{margin:0;font-size:36px;color:#0f172a}label{display:grid;gap:6px;font-weight:700;color:#334155}</style>
