/// <reference types="vite/client" />
export interface RfidCard { id: string; rfid_uid: string; label: string | null }
export interface StudentView { id: string; student_code: string | null; prefix: string | null; first_name: string; last_name: string; nickname: string | null; photo_url: string | null; photo_local_path: string | null; classroom_name: string | null; class_number: number | null; rfid_uids: string | null; rfid_uids_list: string[]; rfid_cards_list: RfidCard[] }
export interface ScanResult { ok: boolean; duplicate?: boolean; event: { client_event_id: string; rfid_uid: string; scanned_at: string; kind: 'entry' | 'exit' }; student: StudentView | null; queue_count: number }
export interface AppConfigView { base_url: string; device_name?: string; device_id?: string; school_code?: string; school_name?: string; role: 'entry' | 'exit' | 'both'; exit_after_hour: string; late_after: string; scan_cooldown_minutes: string; greeting_entry: string; greeting_exit: string; kiosk_lock: string; tts_enabled: string; auto_start: string; app_version?: string; configured: boolean }
export interface ScanHistoryRow { id: number; rfid_uid: string; scanned_at: string; kind: 'entry' | 'exit'; prefix: string | null; first_name: string | null; last_name: string | null; nickname: string | null; classroom_name: string | null; class_number: number | null; photo_url: string | null; photo_local_path: string | null }
export interface UnknownUidRow { rfid_uid: string; count: number; last_scanned_at: string }
export interface HistoryRow { id: number; rfid_uid: string; scanned_at: string; kind: 'entry' | 'exit'; synced: number; sync_error: string | null; first_name: string | null; last_name: string | null; nickname: string | null; classroom_name: string | null }
export interface VerifyPinResult { ok: boolean; locked: boolean; retry_in_s: number }
export interface ClockSkew { skew_ms: number; checked_at: string }
export interface DailySummaryClass { classroom_name: string; total: number; present: number; late: number; exited: number }
export interface DailySummary { late_after: string; totals: { students: number; present: number; late: number; exited: number; absent: number }; classes: DailySummaryClass[] }
declare global { interface Window { krudee: { config: { get(): Promise<AppConfigView> }; setup: { register(payload: Record<string, string>): Promise<{ ok: boolean; device_id: string; school: unknown }> }; scan: { record(payload: { uid: string; scanned_at?: string }): Promise<ScanResult>; queueCount(): Promise<number>; history(): Promise<ScanHistoryRow[]> }; sync: { now(): Promise<unknown>; roster(): Promise<{ count: number }> }; device: { rfidStatus(): Promise<{ connected: boolean; count: number }>; clockSkew(): Promise<ClockSkew | null>; onRfidStatusChange(cb: (status: { connected: boolean; count: number }) => void): () => void }; admin: { verifyPin(pin: string): Promise<VerifyPinResult>; students(query?: string): Promise<StudentView[]>; unknownUids(): Promise<UnknownUidRow[]>; dailySummary(): Promise<DailySummary>; bindCard(payload: { student_id: string; rfid_uid: string; label?: string }): Promise<{ ok: boolean }>; unbindCard(payload: { card_id: string }): Promise<{ ok: boolean }>; clearUnknownUids(): Promise<{ ok: boolean }>; deleteUnknownUid(uid: string): Promise<{ ok: boolean }>; updateSettings(payload: Record<string, string>): Promise<AppConfigView>; history(): Promise<HistoryRow[]>; resetDevice(): Promise<{ ok: boolean }>; devClearScans(): Promise<{ ok: boolean; error?: string }> }; updater: { onUpdateAvailable(cb: (info: { version: string; releaseNotes: string | null }) => void): () => void; onDownloadProgress(cb: (progress: { percent: number }) => void): () => void; onUpdateDownloaded(cb: (info: { version: string }) => void): () => void; install(): Promise<void> } } } }
